// Generated by `npm run sync` from contracts/deployments. Do not edit by hand.
import type { Address } from "viem";

export type Deployment = {
  chainId: number;
  startBlock: number;
  mockAusd: boolean;
  ausd: Address;
  forwarder: Address;
  kinpot: Address;
};

export const deployments: Record<number, Deployment> = {
  "31337": {
    "ausd": "0xa1e4BaB1Ca77271a50C3012f861679576bF95D6f",
    "chainId": 31337,
    "forwarder": "0x08926B57c8fec6a935aE94BbfaED03266029A2fF",
    "kinpot": "0x0C9131bebCc64148efB2A68cE8ce86Ec0d0eB8B6",
    "mockAusd": true,
    "startBlock": 0
  }
};
