// Regenerates src/lib/abi.ts and src/lib/deployments.ts from the Foundry output.
// Run `forge build` (and a deploy, for new addresses) first.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";

const contracts = new URL("../../contracts/", import.meta.url);
const abi = (path) => JSON.parse(readFileSync(new URL(`out/${path}`, contracts), "utf8")).abi;

writeFileSync(
  new URL("../src/lib/abi.ts", import.meta.url),
  [
    "// Generated by `npm run sync` from contracts/out. Do not edit by hand.",
    "",
    `export const kinpotAbi = ${JSON.stringify(abi("Kinpot.sol/Kinpot.json"), null, 2)} as const;`,
    "",
    `export const forwarderAbi = ${JSON.stringify(abi("ERC2771Forwarder.sol/ERC2771Forwarder.json"), null, 2)} as const;`,
    "",
    `export const mockAusdAbi = ${JSON.stringify(abi("MockAUSD.sol/MockAUSD.json"), null, 2)} as const;`,
    "",
  ].join("\n"),
);

const dir = new URL("deployments/", contracts);
const deployments = {};
if (existsSync(dir)) {
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".json"))) {
    const d = JSON.parse(readFileSync(new URL(file, dir), "utf8"));
    deployments[d.chainId] = d;
  }
}
writeFileSync(
  new URL("../src/lib/deployments.ts", import.meta.url),
  [
    "// Generated by `npm run sync` from contracts/deployments. Do not edit by hand.",
    'import type { Address } from "viem";',
    "",
    "export type Deployment = {",
    "  chainId: number;",
    "  startBlock: number;",
    "  mockAusd: boolean;",
    "  ausd: Address;",
    "  forwarder: Address;",
    "  kinpot: Address;",
    "};",
    "",
    `export const deployments: Record<number, Deployment> = ${JSON.stringify(deployments, null, 2)};`,
    "",
  ].join("\n"),
);
console.log("wrote src/lib/abi.ts and src/lib/deployments.ts for chains:", Object.keys(deployments).join(", ") || "none");
